# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-yoctolabs"
BBFILE_PATTERN_meta-yoctolabs = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-yoctolabs = "7"

LAYERDEPENDS_meta-yoctolabs = "core"
LAYERSERIES_COMPAT_meta-yoctolabs = "scarthgap"
