require conf/distro/poky.conf

DISTRO_NAME = "My Super Custom Distro"
DISTRO_VERSION = "1.0.0"

DISTRO_FEATURES:append = " rauc"

DISTRO_FEATURES:append = " systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
INIT_MANAGER = "systemd"
